### ISSUE TITLE
Version 1.4 - Fishfood - Changelog

### ISSUE THREAD

**Issue by JCharante** [baxter-cs/AndOre#169]
Prefix: Due to Milestone's descriptions not supporting markdown, the milestone descriptions will be stored in an issue.

Expansion Description:
- [x] - You can now deconstruct buildings and get 1/3 (rounded down) of the build cost back in the form as lootable ore. (https://github.com/baxter-cs/AndOre/issues/190)
- [x] - The start for multiple worlds has begun with the world server being split up into two. (https://github.com/baxter-cs/AndOre/issues/92)
- [x] - You are now told if you entered the wrong password (https://github.com/baxter-cs/AndOre/issues/197)
- [x] Changed starting ore amount to 250 ore
- [x] You now start with 6 Health Potions
